### ISSUE TITLE
Adding Ansys Python Manager User Guide

### ISSUE THREAD

**Issue by abhishekchitwar** [ansys/python-installer-qt-gui#127]
### 📝 Description of the feature

Inclusion of User guide on Ansys Python Manager.

### 💡 Steps for implementing the feature

Markdown file

**Comment by RobPasMue** [comment]
Hi @abhishekchitwar! Yeah, great idea. Let's do that. Let's include it in our docs. I would add  it to the main landing page of our documentation, and move the existing landing page to a new tab called "Getting started". What do you think?
