### ISSUE TITLE
Install Python fails when install path contains whitespace (and probably other nonstandard characters too)

### ISSUE THREAD

**Issue by mhaisma** [ansys/python-installer-qt-gui#129]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

PowerShell Start-Process fails with "positional parameter cannot be found" when installing to path which includes white space.

The user path in my windows VM is C:\Users\John Smith\

When I try to install python, using any combination of options (any available versions, Standard vs. MiniForge, etc.) with this user login, the installation fails with the following error message:

---------------------------
Error while installing Python!
---------------------------
Error message:

 Start-Process : A positional parameter cannot be found that accepts argument 
'Smith\AppData\Local\ansys_python_installer\ansys_python_installer\Cache\python-3.11.3-amd64.exe'.
At line:1 char:2
+ (Start-Process C:\Users\John Smith\AppData\Local\ansys_python_install ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Start-Process], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.StartProcessCommand
 

---------------------------
OK   
---------------------------

My guess is that this path needs double quotation marks.

### 📝 Steps to reproduce

1. Create a user account named "John Smith" such that the user path is C:\Users\John Smith\
2. Login as John Smith, and Run Ansys Python Manager
3. Install Python using default selections

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
It does not get to the point of installing any packages
```

**Comment by RobPasMue** [comment]
Hi @mhaisma! Thanks for reporting this issue. Let me work on this as soon as I can.

**Comment by RobPasMue** [comment]
Hi @mhaisma! This issue has been addressed with #140 - it will be added in the next release, once we close issue #136

**Comment by RobPasMue** [comment]
Hi @mhaisma - latest released version should include your fix https://github.com/ansys/python-installer-qt-gui/releases/tag/v0.2.8
