### ISSUE TITLE
Ansys Python Manager error at start

### ISSUE THREAD

**Issue by giovannipappalardiansys** [ansys/python-installer-qt-gui#136]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Hi @RobPasMue 
The customer has downloaded the newest Ansys Python Manager (APM) version.
At first start, the APM's GUI appeared, and the customer clicked on Python 3.11 and clicked "Install".

![APM_Install](https://github.com/ansys/python-installer-qt-gui/assets/117667259/c1e511b1-ae34-459c-896e-220a7d8eab2e)

After that, an error appeared and since then it is not possible to use APM because the error appears everytime.

![APM_issue](https://github.com/ansys/python-installer-qt-gui/assets/117667259/eaaaf0d6-2fb4-43a4-b5ae-20a5bac852a7)

### 📝 Steps to reproduce

Install APM,
Lancuh APM
Click Python 3.11+Install
The error will be printed

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

v2023R2

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
No packages installed due to the mentioned error
```

**Comment by RobPasMue** [comment]
Thanks @giovannipappalardiansys - let me look into this :)

**Comment by RobPasMue** [comment]
Hi @giovannipappalardiansys - let's do a test first

Can you ask the customer to run the following on a powershell?

```ps
Invoke-RestMethod -Uri https://pypi.python.org/pypi/pyansys/json
```

Ask them to send you the response back. Thanks!

**Comment by RobPasMue** [comment]
Closing issue after taking in private with @giovannipappalardiansys - customer was having issues on their machines due to permissions
