### ISSUE TITLE
Update Ansys Python Manager to Install Latest Patch Versions

### ISSUE THREAD

**Issue by anssakthi** [ansys/python-installer-qt-gui#260]
### 📝 Description of the feature

During discussions, it was suggested that the Ansys Python Manager should install the latest patch or a minimum of the latest patch minus 2. 

### 💡 Steps for implementing the feature

Explore the possibility of creating a dependency bot that automatically checks for the latest version and updates the code accordingly. This would ensure that the Ansys Python Manager installs the most up-to-date patch versions as recommended.

**Comment by landon-kanner** [comment]
I just tested and installer is still installing 3.8.10.  Do I need to wait for the dependabot to run?

**Comment by RobPasMue** [comment]
Hi @landon-kanner - couple of things.

Not all Python releases are available on Windows. If you go to https://www.python.org/downloads/windows/ and search on the browser for "Python 3.8" you will see that the latest one that has executables is 3.8.10. We could download 3.8.19, but that would imply that users have to build Python from scratch which defeats the purpose of this app for Windows.

Also, these changes are not released yet so you would have to try them out on the main branch.
