### ISSUE TITLE
Fedora build appears to be broken

### ISSUE THREAD

**Issue by RobPasMue** [ansys/python-installer-qt-gui#273]
See latest fedora builds @anssakthi @tusharbana-ansys 

https://github.com/ansys/python-installer-qt-gui/actions/runs/8889896422/job/24408993949

Could you guys look into this?

**Comment by tusharbana-ansys** [comment]
PR for the fix - https://github.com/ansys/python-installer-qt-gui/pull/274
Lets get this merged
