### ISSUE TITLE
Bug located in ...console launched from PyAnsys Manager having Open SSL issues while trying run pyansys scripts

### ISSUE THREAD

**Issue by agvarghe** [ansys/python-installer-qt-gui#343]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

While trying to run a PyPrimeMesh script from a console generated from Python Manager , i am observing Open SSL issue.

The error message is as follows 
`(Py3119_PyAnsys242) D:\Temp\12_CurvatureProximity>python simple.py

Welcome to Ansys Prime Meshing (2024R2)
Copyright 1987 - 2024 ANSYS,Inc. All Rights Reserved.
Starting Ansys Prime Server...
Server listening on : 127.0.0.1:54814
importing CAD...
**legacy Provider loading failed
EVP_DecryptInit. could not load the shared library**
Traceback (most recent call last):
  File "D:\Temp\12_CurvatureProximity\simple.py", line 11, in <module>
    mesh_util.read(file_name=mixing_elbow)
  File "C:\Users\hgrotjan\.ansys_python_venvs\Py3119_PyAnsys242\Lib\site-packages\ansys\meshing\prime\lucid\mesh_util.py", line 114, in read
    prime.FileIO(self._model).import_cad(
  File "C:\Users\hgrotjan\.ansys_python_venvs\Py3119_PyAnsys242\Lib\site-packages\ansys\meshing\prime\core\fileio.py", line 586, in import_cad
    import_result = super().import_cad(temp_file_name, params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hgrotjan\.ansys_python_venvs\Py3119_PyAnsys242\Lib\site-packages\ansys\meshing\prime\autogen\fileio.py", line 692, in import_cad
    result = self._comm.serve(self._model, command_name, self._object_id, args=args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hgrotjan\.ansys_python_venvs\Py3119_PyAnsys242\Lib\site-packages\ansys\meshing\prime\internals\error_handling.py", line 577, in wrapper_error_code
    raise PrimeRuntimeError(
ansys.meshing.prime.internals.error_handling.PrimeRuntimeError: CAD import failed.
 `

### 📝 Steps to reproduce

1. Create a vitrual env on python 3.11.9 using python manager
2. Install pyprimemesh module
3. Launch console from Python Manager and try running any PyPrimeMesh examples

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R2

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
Package                 Version
----------------------- -----------
ansys-api-meshing-prime 0.1.3
ansys-meshing-prime     0.6.2
appdirs                 1.4.4
certifi                 2024.8.30
charset-normalizer      3.3.2
contourpy               1.3.0
cycler                  0.12.1
fonttools               4.53.1
grpcio                  1.66.1
idna                    3.8
kiwisolver              1.4.6
matplotlib              3.9.2
numpy                   2.1.1
packaging               24.1
pillow                  10.4.0
pip                     24.0
platformdirs            4.2.2
pooch                   1.8.2
protobuf                4.25.4
pyparsing               3.1.4
python-dateutil         2.9.0.post0
pyvista                 0.44.1
requests                2.32.3
scooby                  0.10.0
setuptools              65.5.0
six                     1.16.0
typing_extensions       4.12.2
urllib3                 2.2.2
vtk                     9.3.1
```

**Comment by RobPasMue** [comment]
Can you share the exact code you are trying to run @agvarghe?

**Comment by agvarghe** [comment]
Hi @RobPasMue 

Please do find the file attached herewith.

[Rhino_import.zip](https://github.com/user-attachments/files/16861720/Rhino_import.zip)

**Comment by RobPasMue** [comment]
Thanks @agvarghe - I will try to replicate it on my side... however, I think this might be a machine issue.
