### ISSUE TITLE
[BUG] virtual environment created from installer does not allow for Fluent 24R2 to be launched

### ISSUE THREAD

**Issue by rploconnor** [ansys/python-installer-qt-gui#375]
### 🔍 Before submitting the issue

- [x] I have tried the latest Ansys Python Installer version
- [x] I have adapted properly the title of the issue

### Description

Steps to reproduce:
1) Install latest installer
2) From installer, install Python (version doesn't matter)
3) From installer, create virtual environment
4) From installer, install pyfluent (version doesn't matter)
5) From installer, Launch console 
6) From console, launch Fluent as follows: start "" "C:\Program Files\ANSYS Inc\v242\fluent\ntbin\win64\fluent.exe" 3ddp -t2 -sifile=serverinfo.txt -nm
7) Fluent opens and then shuts down. Error in the Fluent transcript is as follows: 

legacy Provider loading failed 
EVP_DecryptInit. could not load the shared library

Everything works fine if I launch from a virtual environment created manually.
Everything works fine if I launch a version of Fluent 24R1 and older.

**Comment by phx-mkoninckx** [comment]
@rploconnor: I believe this may be the result of a broader issue with `pyinstaller` that we can work around. See #376, I'm happy to answer any questions you may have about it.

**Comment by RobPasMue** [comment]
Might be related like @phx-mkoninckx mentions, @rploconnor - can you give it a try to this version of the installer? https://github.com/ansys/python-installer-qt-gui/pull/377

You can download it from the workflow artifacts
