### ISSUE TITLE
[BUG] Problem found during Launch VSCode

### ISSUE THREAD

**Issue by wkozek** [ansys/python-installer-qt-gui#400]
### 🔍 Before submitting the issue

- [x] I have tried the latest Ansys Python Installer version
- [x] I have adapted properly the title of the issue

### Description

I tried to run from the manager VSCode

It ended with the error: 
  'code' is not recognized as an internal or external command,
  operable program or batch file.
  Failed to launch vscode. Try reinstalling code by following this link https://code.visualstudio.com/download

I tried to reinstall vscode > start from cmd with 'code' works without problem. 
When I am using manager > still same error.

**Comment by RobPasMue** [comment]
HI @wkozek - thanks for opening this issue. Did you restart you machine and try again via the Ansys Python Manager (after having reinstalled VSCode)?

Also, can you give more information on your setup? (Windows/Linux, version, user or admin install of the app...)

**Comment by wkozek** [comment]
Hello Roberto,

I found a solution: I cleaned all the paths in sysdm. Cpl> Advanced > Environment Variables > Path and provided them once again. After restarting Windows, everything worked fine.

So sorry for creating a new Bug report. However, maybe the solution will be useful to someone in the future.

Kind Regards

Wojciech Kozek

Thermal&Fluid Systems Simulation Engineer
BorgWarner Emissions, Thermal and Turbo Systems

BorgWarner Poland Sp. z o.o.
36-002 Jasionka 950
***@***.******@***.***>

**Comment by RobPasMue** [comment]
> Hello Roberto, I found a solution: I cleaned all the paths in sysdm. Cpl> Advanced > Environment Variables > Path and provided them once again. After restarting Windows, everything worked fine. So sorry for creating a new Bug report. However, maybe the solution will be useful to someone in the future.

Awesome, thanks a bunch @wkozek! Closing issue in that case. And thanks for reporting it! I'm sure it'll help other users!

**Comment by Methy2548** [comment]
Hi, 

I'm still having the issue. I'm on Windows 11 with the use setup of VSCode.

Help would be appreciated thanks!

**Comment by RobPasMue** [comment]
Hi @Methy2548 - did you try the above solution? https://github.com/ansys/python-installer-qt-gui/issues/400#issuecomment-2540773342

If that did not work, please open a new issue and explain in depth your problem. Thanks!
